# Generated by Django 5.0.2 on 2024-03-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameWebsite', '0006_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='checkUser',
            field=models.BooleanField(default=True),
        ),
    ]
