# Generated by Django 5.0.2 on 2024-03-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameWebsite', '0010_profile_hangman_game_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='snake_game_1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='snake_game_2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='snake_game_3',
            field=models.BooleanField(default=True),
        ),
    ]
