# Generated by Django 5.0.2 on 2024-03-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameWebsite', '0011_profile_snake_game_1_profile_snake_game_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='snake_game_3',
            new_name='momory_card_1',
        ),
        migrations.AddField(
            model_name='profile',
            name='momory_card_2',
            field=models.BooleanField(default=True),
        ),
    ]
