# Generated by Django 5.0.3 on 2024-03-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameWebsite', '0014_profile_purchase_1_profile_purchase_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='claim_daily_coin',
            field=models.BooleanField(default=False),
        ),
    ]
