# Generated by Django 5.0.2 on 2024-03-29 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameWebsite', '0015_profile_claim_daily_coin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='car_1',
            new_name='ping_pong_1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='car_2',
            new_name='ping_pong_2',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='car_game_count',
            new_name='ping_pong_count',
        ),
    ]
